# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    # allowed_methods_listener:  true
    # routing_loader: true
    view:
        view_response_listener:  true
        formats:
            json: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, html ], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
    body_converter:
        enabled: true
        validate: true
